### ISSUE TITLE
Перестаёт работать переключение между режимом перемещения и обычным

### ISSUE THREAD

**Issue by levovix0** [mastertimer/mutator#1]
Если сохранить мутатор, когда включен режим перемещения, при следующем запуске перестаёт работать переключение между режимом перемещения и обычным, и вообще всё. 
(Запускается сразу в режиме перемещения)

**Comment by mastertimer** [comment]
никогда так не сохранял. но стоит исправить

**Comment by mastertimer** [comment]
исправил
