### ISSUE TITLE
Баг отрисовки

### ISSUE THREAD

**Issue by stalker57241** [mastertimer/mutator#11]
Проверяя работоспособность программы заметил, что при сильном удалении от объекта он начинает оставлять следы за собой в виде зеленых пятен что размазываются по экрану. Как вариант можно заново перерисовывать всю картинку, а точнее рисовать черный фон. Вот так выглядит картинка.
![Screenshot_23](https://user-images.githubusercontent.com/40300537/82942626-eabc1580-9fa0-11ea-8846-580e4417aaa4.png)

**Comment by mastertimer** [comment]
у меня такого бага не наблюдается...

**Comment by mastertimer** [comment]
можешь поисследовать, описать подробнее и заново открыть, если будет продолжаться. у меня не единого следа ни остается... может у тебя версия какая-то промежуточная?

**Comment by levovix0** [comment]
Я взял самую последнюю и включил отображение времени. ![](https://i0.wampi.ru/2020/06/02/ANNOTATIY-2020-06-02-150803.png)

**Comment by mastertimer** [comment]
время отображения - это отладочная информация, отображается вообще не по правилам. так что это не считается))
