### ISSUE TITLE
Отображать подсказки в другом месте

### ISSUE THREAD

**Issue by levovix0** [mastertimer/mutator#14]
Сейчас подсказки отображаются так:
![](https://ia.wampi.ru/2020/06/02/ANNOTATIY-2020-06-02-150803ee40088724f532f3.png)
Было бы неплохо если бы их было видно и они хотя бы читались
Можно отображать некоторые подсказки под курсором,
Или в пустом месте,
Или сделать им тени

**Comment by mastertimer** [comment]
сделал подсказки более заметными
