### ISSUE TITLE
Улетает в лево

### ISSUE THREAD

**Issue by Mostich** [mastertimer/mutator#15]
При сильном отдолении, и нажатии на circle-toolbar приведение к нормальному размеру, все элементы улетаю далеко в лево, и кажется что все объекты исчезли.

**Comment by levovix0** [comment]
Камера центрируется на курсоре

**Comment by Mostich** [comment]
У меня курсор по центру всех элементов, просто отдаляюсь далеко, а он все равно в лево смещает. Ну или я что-то не так делаю

**Comment by mastertimer** [comment]
Сам открыл, Сам закрыл)) На самом описанное неприятно. И я давным давно еще думал ввести еще одну дополнительную кнопку на колесе, которая центрирует и масштабирует так, чтобы вся графика поместилась на экране
