### ISSUE TITLE
Баг увеличения графа тетронов

### ISSUE THREAD

**Issue by Mostich** [mastertimer/mutator#16]
![изображение](https://user-images.githubusercontent.com/51542168/83873839-30b17000-a73d-11ea-8f58-dd127d0cd404.png)
Если долго углублятся в граф тетронов, то начнет мотать или перекидывать из стороны в сторону. Потом будет невозможно двигаться с помощью circle-toolbar. А при открытии он появляется не около курсора а выборочно, и в большинстве случаев он появляется не целый. Было бы понятно, если лаги были вызваны большим количество информации или большой нагрузкой на процессор, но ни того ни другого нет. А если увеличивать еще дальше circle-toolbar пропадает совсем и больше не открывается. Нагрузка 0%, ОЗУ 11Мб

**Comment by mastertimer** [comment]
Это происходит переполнение переменной double, в которой хранится смещение. Похоже ты увеличил в квадриллион раз)) Решение этой проблемы - использовать длинную арифметику.

**Comment by mastertimer** [comment]
сделал ограничение для увеличения
