### ISSUE TITLE
Документация(Wiki)

### ISSUE THREAD

**Issue by Mostich** [mastertimer/mutator#20]
Как на счет постепенного составления документации?
Чем больше проект тем сложнее будет в дальнейшем разобраться с устройством проекта новым участникам, кто захочет помочь в разработке.

Если хотите я могу заняться составлением FAQ(Часто задаваемые вопросы). И нахождением на них ответов на стримах. Составлением терминов в mutator'e - Что такое Тетрон, Фрогриф и т.д. А потом можно отредактировать для более точного описания термина. 
И начать оформлять все это в раздел Wiki.

**Comment by mastertimer** [comment]
Вроде сделал доступ редактирования Wiki для всех. Можешь делать FAQ
