### ISSUE TITLE
Графический баг

### ISSUE THREAD

**Issue by levovix0** [mastertimer/mutator#3]
Отображаются одновременно и миниатюры тетронов, и их граф
Вот так это выглядит: [скриншот](https://s8.wampi.ru/2020/02/14/IZOBRAZENIE.png)

Также сильно виснет при отображении графа главного графического тетрона. секунд 5 не отвечает.

**Comment by mastertimer** [comment]
с этим борюсь, уже несколько дней, еще не поборол...

**Comment by mastertimer** [comment]
вроде победил... хорошая точка для паузы! делаю перерыв на 3 недели.
