### ISSUE TITLE
При попытке переместить полосу прокрутки в пространстве вылетает мутатор

### ISSUE THREAD

**Issue by levovix0** [mastertimer/mutator#4]

**Comment by mastertimer** [comment]
такого не наблюдал. где при каких условиях это происходит?

**Comment by levovix0** [comment]
Выделяешь полосу прокрутки, пытаешься её сдвинуть -> вылетает

**Comment by mastertimer** [comment]
снова одно из действий, которое я никогда не пробовал делать, т.к. ползунок обладает свойством автоматически прилипать к родительскому объекту.. но нужно исправить! пусть он или перемещается, или не перемещается, но мутатор не должен вылетать!))

**Comment by mastertimer** [comment]
исправил тем, что пока запретил такие действия.
