### ISSUE TITLE
Проблемы с изменением размера

### ISSUE THREAD

**Issue by levovix0** [mastertimer/mutator#7]
1. Если уменьшить ширину/высоту любого графического объекта до нуля, его будет невозможно выделить снова, даже если очень сильно приблизить.
2. Рамка выделения слишком маленькая (1 пиксель), в неё тяжело попасть.
3. Нет возможности изменять размер объекта за левую и верхнюю грань, и тем более за углы.
4. Не совпадает размер шрифта и размер курсора в однострочном поле ввода, если изменить его размер. ![ссылка](https://i9.wampi.ru/2020/04/01/2020-04-01_19-18.png) (возможно, было бы логично изменять размер шрифта вместе с вертикальным размером рамки)
5. Не совпадает размер кнопки и размер её иконки (картинка даже не растягивается). ![ссылка](https://i9.wampi.ru/2020/04/01/2020-04-01_19-184730f14dd2ffffb3.png)
6. Не изменяется размер рамки выделения холста при изменении размеров холста с помощью кнопки.
7. Не изменяется фактический размер картинки, при изменении размеров холста с помощью рамки выделения. (холст даже не растягивается). если уменьшить холст, станет невидимой часть картинки.

**Comment by mastertimer** [comment]
1. сделан запрет уменьшения до нуля, но лучше в будущем сделать возможным выделения объектов нулевой ширины
2. чуть расширил
3.пусть будет как было
4. курсор исправил
5. пусть будет как было
6. --- нужно сделать
7. --- нужно сделать

**Comment by mastertimer** [comment]
Если сильно раздражает, то создай по одному сообщению на один глюк. В принципе холст для меня не в приоритете. постоянно подумываю, чтобы вообще его удалить, а для кнопок использовать только надписи и фроглифы...
