### ISSUE TITLE
Пустые тетроны

### ISSUE THREAD

**Issue by levovix0** [mastertimer/mutator#8]
Я создал GRect, выделил его, приблизил до первого уровня видимости графа. в земной панели выбрал и перешёл на другой тетрон по связи. снова выделил GRect, приблизил, и получил ![вот это](https://i9.wampi.ru/2020/04/22/mutator-error-5.png).  
Становится снова нормальным, если выделить другой графический объект.

**Comment by levovix0** [comment]
Ещё вариант этой ошибки. выделил кнопку, приблизил граф, нажал на него левой кнопкой мыши (не в режиме перемещёния). получил [вот это](https://i9.wampi.ru/2020/04/22/mutator-error-5-2.png).

**Comment by mastertimer** [comment]
это скорее всего связано с неправильной чисткой звезд. у меня эта ошибка отмечена. Её можно заметить по тому, что количество тетронов не возвращается в норму после того, как граф уже не отображается.

**Comment by mastertimer** [comment]
надеюсь, исправил...
