### ISSUE TITLE
битые пиксели

### ISSUE THREAD

**Issue by levovix0** [mastertimer/mutator#9]
навёл курсор на кнопку. зажал ПКМ, и, не опуская, отодвинул на пустое место, опустил. передвинул курсор.
рядом с правым верхним углом кнопки можно увидеть ![один или пару лишних пикселей](https://i0.wampi.ru/2020/05/17/ANNOTATIY-2020-05-17-215249.png)

**Comment by mastertimer** [comment]
знаю об этом глюке. это кусок текста подсказки. почему-то при рисовании если указать координату x, он залазит и на x-1.

**Comment by mastertimer** [comment]
исправил
